version: "3.9"

services:
  java_db:
    image: postgres:16-alpine
    restart: always
    container_name: java_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres